name: 'pull_request'
on: ['pull_request']

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: 'actions/checkout@v1'

    - name: 'Test'
      run: 'echo "ok"'

    # - name: 'Build'
    #   run: 'docker build -t myapp .'
    # - name: 'Push'
    #   run: 'docker push myapp'
